#!/system/bin/sh
#
# init_wrapper
#
#
# 2011 nubecoder
# http://www.nubecoder.com/
#
# Modeled after Bonsai's init_wrapper script
# Bits taken from DRockstar's Clean Kernel sdx.sh script

/sbin/busybox mount -o remount,rw / /
/sbin/busybox mount -o remount,rw /dev/block/stl9 /system

# Install busybox
/sbin/busybox mkdir /bin
/sbin/busybox --install -s /bin
rm -rf /system/xbin/busybox
ln -s /sbin/busybox /system/xbin/busybox
rm -rf /res
sync

# Fixing permissions and ownership
chmod 755 /sbin/*
for blip in conf default.prop fota.rc init init.goldfish.rc init.rc init.smdkc110.rc lib lpm.rc modules recovery.rc res sbin
do
	chown root.system /$blip
	chown root.system /$blip/*
done
chown root.system /lib/modules/*
chown root.system /res/images/*

chmod 6755 /sbin/su

if [ -f /system/bin/su ]; then
	rm -f /system/bin/su
	ln -s /sbin/su /system/bin/su
fi

if [ -x /system/xbin/su ]; then
	rm -f /system/xbin/su
	ln -s /sbin/su /system/xbin/su
fi

if [ -f /system/bin/jk-su ]; then
	rm -f /system/bin/jk-su
fi

# Setup proper passwd and group files for 3rd party root access
if [ ! -f "/system/etc/passwd" ]; then
	echo "root::0:0:root:/data/local:/sbin/sh" > /system/etc/passwd
	chmod 0400 /system/etc/passwd
fi

if [ ! -f "/system/etc/group" ]; then
	echo "root::0:" > /system/etc/group
	chmod 0400 /system/etc/group
fi

# Ensure Superuser is installed to protect root access
if [ ! -f "/system/app/Superuser.apk" && ! -f "/data/app/Superuser.apk" ]; then
	cp /sbin/Superuser.apk /system/app/Superuser.apk
fi
rm /sbin/Superuser.apk

# Prevent certain malware apps (DroidDream)
. > /system/bin/profile
chmod 644 /system/bin/profile

# Fixing busybox DNS
if [ ! -f "/system/etc/resolv.conf" ]; then
	echo "nameserver 8.8.8.8" >> /system/etc/resolv.conf
	echo "nameserver 8.8.4.4" >> /system/etc/resolv.conf
fi

sync

mount -o remount,ro / /
mount -o remount,ro /dev/block/stl9 /system
