#!/sbin/busybox sh
#
# mount_ro
#
#
# 2011 nubecoder
# http://www.nubecoder.com/
#

#functions
SEND_LOG()
{
	log -p i -t init:mount_ro "mount_ro : $1"
}

#main
SEND_LOG "Start"

# Wait for cleanup to finish
SEND_LOG "Waiting for clean_init to finish"
while /sbin/busybox test -f "/sbin/clean_init" ; do
	SEND_LOG "Sleep 1"
	sleep 1
done

SEND_LOG "Remount ro"
# Remount as RO
/sbin/busybox mount -o remount,ro /
/sbin/busybox mount -o remount,ro /system

SEND_LOG "End"

