#!/sbin/busybox sh
#
# recovery_wrapper
#
#
# 2011 nubecoder
# http://www.nubecoder.com/
#
# Bonsai's init_wrapper script used as a base
# Other bits taken from the following people:
# Tanimn, DRockstar, Rodderik

#functions
SEND_LOG()
{
	log -p i -t init:recovery_wrapper "recovery_wrapper : $1"
}

#main
SEND_LOG "Start"

SEND_LOG "Remount as rw"
/sbin/busybox mount -o remount,rw /

SEND_LOG "Installing busybox to /sbin"
/sbin/busybox --install -s /sbin

SEND_LOG "Syncing filesystem"
sync

SEND_LOG "Moving recovery assets to /sbin"
mv -f /res/sbin/* /sbin/

SEND_LOG "Moving recovery.fstab to /etc"
mkdir /etc
mv -f /res/etc/recovery.fstab /etc/recovery.fstab

SEND_LOG "Remove unneccessary files"
for FILE in Superuser.apk keytimer mount_ro
do
	SEND_LOG "  rm -f /sbin/$FILE"
	rm -f /sbin/$FILE
done
for FOLDER in res/sbin ; do
	SEND_LOG "  rm -rf $FOLDER"
	rm -rf /$FOLDER
done
#rmdir /res/etc

SEND_LOG "Fixing permissions and ownership"
SEND_LOG "chmod 0755 /sbin/*"
chmod 0755 /sbin/*
for FILE in default.prop init init.sh init.smdkc110.rc ; do
	SEND_LOG "  chown root.system /$FILE"
	chown root.system /$FILE
done
for FOLDER in conf lib lib/modules modules res res/images sbin ; do
	SEND_LOG "  chown root.system /$FOLDER"
	chown root.system /$FOLDER
	SEND_LOG "  chown root.system /$FOLDER/*"
	chown root.system /$FOLDER/*
done

SEND_LOG "Sync filesystem"
sync

SEND_LOG "Remove self"
rm -f "/sbin/recovery_wrapper"

SEND_LOG "Execute recovery binary"
/sbin/recovery

SEND_LOG "End"

