#!/sbin/busybox sh
#
# recovery_wrapper
#
#
# 2011 nubecoder
# http://www.nubecoder.com/
#
# Bonsai's init_wrapper script used as a base
# Other bits taken from the following people:
# Tanimn, DRockstar, Rodderik

# Remount as RW
/sbin/busybox mount -o remount,rw / /

# Install busybox to /sbin
/sbin/busybox --install -s /sbin

# Sync filesystem
sync

# Move recovery assets to /sbin
mv -f /res/sbin* /sbin/

# Move recovery.fstab to proper location
mkdir /etc
mv -f /res/etc/recovery.fstab /etc/recovery.fstab

# Remove unneccessary files
for file in Superuser.apk su keytimer
do
	rm -rf /sbin/$file
done
rmdir /res/sbin
#rmdir /res/etc

# Fixing permissions and ownership
chmod 0755 /sbin/*
for blip in conf default.prop fota.rc init init.sh init.rc init.rc.sdcard init.smdkc110.rc lib lib/modules lpm.rc modules recovery.rc res res/images sbin
do
	chown root.system /$blip
	chown root.system /$blip/*
done

# Sync filesystem
sync

# Execute recovery binary
/sbin/recovery

